# Generated by Django 4.2.2 on 2023-06-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_crawling_crawling_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawling',
            name='link',
            field=models.CharField(default='/', max_length=50),
        ),
    ]
